module.exports = {
  extends: [
    "stylelint-config-standard"
  ],
  plugins: ["stylelint-order", "stylelint-scss"],
  ignoreFiles: ["*.vue", "*.scss", "*.css"],
  defaultSeverity: "error",
  // add your custom config here
  // https://stylelint.io/user-guide/configuration
  rules: {
    // 禁止使用未知规则
    "at-rule-no-unknown": [
      null,
      {
        ignoreAtRules: ["mixin", "include"]
      }
    ],
    // 禁止使用媒体功能名称的供应商前缀
    "media-feature-name-no-vendor-prefix": true,
    // 禁止覆盖较低特异性的选择器，而不是覆盖较高特异性的选择器
    "no-descending-specificity": null,
    // 禁止使用未知的伪元素选择器
    "selector-pseudo-element-no-unknown": null,
    // 禁止使用多余的分号
    "no-extra-semicolons": true,
    // 在功能的逗号后面需要一个空格
    "function-comma-space-after": "always",
    // 在冒号声明后必须有一个空格
    "declaration-colon-space-after": "always",
    // 禁止重复的字体系列名称
    "font-family-no-duplicate-names": true,
    // 禁止在calc函数内使用无效的表达式
    "function-calc-no-invalid": true,
    // 限制数字中允许的小数位数
    "number-max-precision": 2,
    // 指定时间值的最小毫秒数
    "time-min-milliseconds": 1,
    // 禁止在速记属性中使用冗余值
    "shorthand-property-no-redundant-values": true,
    // 限制功能（自动修复）中相邻空行的数量
    "function-max-empty-lines": 0,
    // 在字符串周围指定单引号或双引号
    "string-quotes": "single",
    // 在冒号声明前不允许使用空格
    "declaration-colon-space-before": "never",
    // 在声明块的分号后需要换行符或禁止空格
    "declaration-block-semicolon-newline-after": "always",
    // 在声明块中要求或禁止尾部分号
    "declaration-block-trailing-semicolon": "always",
    // 右大括号后需要换行符
    "block-closing-brace-newline-after": "always",
    // 在规则前需要有空行
    "rule-empty-line-before": "always",
    // 在规则之前要求有空行
    "at-rule-empty-line-before": "always",
    // 指定缩进为两个空格
    indentation: 2,
    "no-invalid-position-at-import-rule": null,
    "no-irregular-whitespace": null,
    "font-family-no-missing-generic-family-keyword": null,
    "order/properties-order": [
      "position",
      "z-index",
      "top",
      "bottom",
      "left",
      "right",
      "float",
      "clear",
      "columns",
      "columns-width",
      "columns-count",
      "column-rule",
      "column-rule-width",
      "column-rule-style",
      "column-rule-color",
      "column-fill",
      "column-span",
      "column-gap",
      "display",
      "grid",
      "grid-template-rows",
      "grid-template-columns",
      "grid-template-areas",
      "grid-auto-rows",
      "grid-auto-columns",
      "grid-auto-flow",
      "grid-column-gap",
      "grid-row-gap",
      "grid-template",
      "grid-template-rows",
      "grid-template-columns",
      "grid-template-areas",
      "grid-gap",
      "grid-row-gap",
      "grid-column-gap",
      "grid-area",
      "grid-row-start",
      "grid-row-end",
      "grid-column-start",
      "grid-column-end",
      "grid-column",
      "grid-column-start",
      "grid-column-end",
      "grid-row",
      "grid-row-start",
      "grid-row-end",
      "flex",
      "flex-grow",
      "flex-shrink",
      "flex-basis",
      "flex-flow",
      "flex-direction",
      "flex-wrap",
      "justify-content",
      "align-content",
      "align-items",
      "align-self",
      "order",
      "table-layout",
      "empty-cells",
      "caption-side",
      "border-collapse",
      "border-spacing",
      "list-style",
      "list-style-type",
      "list-style-position",
      "list-style-image",
      "ruby-align",
      "ruby-merge",
      "ruby-position",
      "box-sizing",
      "width",
      "min-width",
      "max-width",
      "height",
      "min-height",
      "max-height",
      "padding",
      "padding-top",
      "padding-right",
      "padding-bottom",
      "padding-left",
      "margin",
      "margin-top",
      "margin-right",
      "margin-bottom",
      "margin-left",
      "border",
      "border-width",
      "border-top-width",
      "border-right-width",
      "border-bottom-width",
      "border-left-width",
      "border-style",
      "border-top-style",
      "border-right-style",
      "border-bottom-style",
      "border-left-style",
      "border-color",
      "border-top-color",
      "border-right-color",
      "border-bottom-color",
      "border-left-color",
      "border-image",
      "border-image-source",
      "border-image-slice",
      "border-image-width",
      "border-image-outset",
      "border-image-repeat",
      "border-top",
      "border-top-width",
      "border-top-style",
      "border-top-color",
      "border-top",
      "border-right-width",
      "border-right-style",
      "border-right-color",
      "border-bottom",
      "border-bottom-width",
      "border-bottom-style",
      "border-bottom-color",
      "border-left",
      "border-left-width",
      "border-left-style",
      "border-left-color",
      "border-radius",
      "border-top-right-radius",
      "border-bottom-right-radius",
      "border-bottom-left-radius",
      "border-top-left-radius",
      "outline",
      "outline-width",
      "outline-color",
      "outline-style",
      "outline-offset",
      "overflow",
      "overflow-x",
      "overflow-y",
      "resize",
      "visibility",
      "font",
      "font-style",
      "font-variant",
      "font-weight",
      "font-stretch",
      "font-size",
      "font-family",
      "font-synthesis",
      "font-size-adjust",
      "font-kerning",
      "line-height",
      "text-align",
      "text-align-last",
      "vertical-align",
      "text-overflow",
      "text-justify",
      "text-transform",
      "text-indent",
      "text-emphasis",
      "text-emphasis-style",
      "text-emphasis-color",
      "text-emphasis-position",
      "text-decoration",
      "text-decoration-color",
      "text-decoration-style",
      "text-decoration-line",
      "text-underline-position",
      "text-shadow",
      "white-space",
      "overflow-wrap",
      "word-wrap",
      "word-break",
      "line-break",
      "hyphens",
      "letter-spacing",
      "word-spacing",
      "quotes",
      "tab-size",
      "orphans",
      "writing-mode",
      "text-combine-upright",
      "unicode-bidi",
      "text-orientation",
      "direction",
      "text-rendering",
      "font-feature-settings",
      "font-language-override",
      "image-rendering",
      "image-orientation",
      "image-resolution",
      "shape-image-threshold",
      "shape-outside",
      "shape-margin",
      "color",
      "background",
      "background-image",
      "background-position",
      "background-size",
      "background-repeat",
      "background-origin",
      "background-clip",
      "background-attachment",
      "background-color",
      "background-blend-mode",
      "isolation",
      "clip-path",
      "mask",
      "mask-image",
      "mask-mode",
      "mask-position",
      "mask-size",
      "mask-repeat",
      "mask-origin",
      "mask-clip",
      "mask-composite",
      "mask-type",
      "filter",
      "box-shadow",
      "opacity",
      "transform-style",
      "transform",
      "transform-box",
      "transform-origin",
      "perspective",
      "perspective-origin",
      "backface-visibility",
      "transition",
      "transition-property",
      "transition-duration",
      "transition-timing-function",
      "transition-delay",
      "animation",
      "animation-name",
      "animation-duration",
      "animation-timing-function",
      "animation-delay",
      "animation-iteration-count",
      "animation-direction",
      "animation-fill-mode",
      "animation-play-state",
      "scroll-behavior",
      "scroll-snap-type",
      "scroll-snap-destination",
      "scroll-snap-coordinate",
      "cursor",
      "touch-action",
      "caret-color",
      "ime-mode",
      "object-fit",
      "object-position",
      "content",
      "counter-reset",
      "counter-increment",
      "will-change",
      "pointer-events",
      "all",
      "page-break-before",
      "page-break-after",
      "page-break-inside",
      "widows"
    ]
  }
};
